### ISSUE TITLE
Python not detecting auth.txt

### ISSUE THREAD

**Issue by GalaxyTheoryz** [josh-justjosh/Station-Updates#6]
I have put all the keys in the 'auth.txt' in the same directory as the code, however, python does not seem to pick it up and gives the following error:

Traceback (most recent call last):
  File "C:\Users\GalaxyTheoryz\Downloads\KGX\tweeting v2.py", line 19, in <module>
    from auth import (
ModuleNotFoundError: No module named 'auth'

I don't assume I need a module named 'auth'. Here is what the text file looks like:

consumer_key=x
consumer_secret=x
access_token=x
access_token_secret=x
rttapi_username=x
rttapi_password=x
nre_key=x

If you could let me know asap, that would be great. Thanks

**Comment by josh-justjosh** [comment]
Hi there, this appears to be my mistake when writing the readme - it needs to be a python file. Opening the txt file and saving it as a .py file should fix it.

**Comment by josh-justjosh** [comment]
Hey @GalaxyTheoryz,
Just out of interest, what are you using this for? I killed this project last year - you can read the post mortem [here](https://www.josh.me.uk/blog/main/2019-11-02-13-14)

**Comment by GalaxyTheoryz** [comment]
Hey, I'm just going to see if I can run this as a twitter account probably for Doncaster station. I'm planning to see if I can run this every 3 hours or so. How long does it take to tweet by the way, I've got it set up, but just at the moment it is saying 'Still Alive'.

**Comment by josh-justjosh** [comment]
Around line 50, there's a section that deals with when it runs through the sorting algorithm. It's currently set to every five minutes. It can probably be improved with `time.sleep` but for some reason that's not how it did it. Try messing with that and see what you get. Let me know if you manage to get it working!

**Comment by GalaxyTheoryz** [comment]
I'll see what I can do. I am currently looking at running it via a batch file but I'll see if I can get time.sleep to work. I'm not that familiar with the 'twython' module and was wondering how I could put the station name at the top of every tweet, no matter how much I have tried, I've not seemed to have got a result.
